const words = {

englisch: [
["apple","Apfel"],["house","Haus"],["dog","Hund"],["cat","Katze"],["water","Wasser"],
["book","Buch"],["school","Schule"],["car","Auto"],["tree","Baum"],["bread","Brot"],
["milk","Milch"],["sun","Sonne"],["moon","Mond"],["star","Stern"],["city","Stadt"],
["street","Straße"],["phone","Telefon"],["computer","Computer"],["chair","Stuhl"],["table","Tisch"],
["window","Fenster"],["door","Tür"],["flower","Blume"],["garden","Garten"],["friend","Freund"],
["family","Familie"],["love","Liebe"],["work","Arbeit"],["money","Geld"],["time","Zeit"],
["day","Tag"],["night","Nacht"],["food","Essen"],["drink","Getränk"],["animal","Tier"],
["bird","Vogel"],["fish","Fisch"],["mountain","Berg"],["river","Fluss"],["sea","Meer"],
["rain","Regen"],["snow","Schnee"],["cold","Kalt"],["hot","Heiß"],["happy","Glücklich"],
["sad","Traurig"],["big","Groß"],["small","Klein"],["fast","Schnell"],["slow","Langsam"],
["light","Licht"],["dark","Dunkel"],["morning","Morgen"],["evening","Abend"],["breakfast","Frühstück"],
["lunch","Mittagessen"],["dinner","Abendessen"],["cheese","Käse"],["egg","Ei"],["meat","Fleisch"],
["coffee","Kaffee"],["tea","Tee"],["sugar","Zucker"],["salt","Salz"],["pepper","Pfeffer"],
["knife","Messer"],["fork","Gabel"],["spoon","Löffel"],["plate","Teller"],["cup","Tasse"],
["glass","Glas"],["bag","Tasche"],["shirt","Hemd"],["pants","Hose"],["shoe","Schuh"],
["jacket","Jacke"],["hat","Hut"],["watch","Uhr"],["ring","Ring"],["bed","Bett"],
["pillow","Kissen"],["blanket","Decke"],["bathroom","Badezimmer"],["kitchen","Küche"],["floor","Boden"],
["wall","Wand"],["roof","Dach"],["key","Schlüssel"],["lock","Schloss"],["bus","Bus"],
["train","Zug"],["plane","Flugzeug"],["ticket","Ticket"],["station","Bahnhof"],["airport","Flughafen"],
["doctor","Arzt"],["nurse","Krankenschwester"],["hospital","Krankenhaus"],["medicine","Medizin"],["pain","Schmerz"],
["teacher","Lehrer"],["student","Schüler"],["lesson","Unterricht"],["homework","Hausaufgabe"],["exam","Prüfung"],
["game","Spiel"],["ball","Ball"],["team","Team"],["player","Spieler"],["goal","Tor"],
["music","Musik"],["song","Lied"],["movie","Film"],["picture","Bild"],["camera","Kamera"],
["news","Nachrichten"],["paper","Zeitung"],["radio","Radio"],["television","Fernsehen"],["internet","Internet"],
["website","Webseite"],["password","Passwort"],["username","Benutzername"],["button","Knopf"],["screen","Bildschirm"],
["mouse","Maus"],["keyboard","Tastatur"],["file","Datei"],["folder","Ordner"],["download","Download"],
["upload","Upload"],["message","Nachricht"],["chat","Chat"],["call","Anruf"],["voice","Stimme"],
["language","Sprache"],["word","Wort"],["sentence","Satz"],["question","Frage"],["answer","Antwort"],
["idea","Idee"],["plan","Plan"],["problem","Problem"],["solution","Lösung"],["job","Job"],
["boss","Chef"],["office","Büro"],["meeting","Treffen"],["project","Projekt"],["goal","Ziel"],
["holiday","Urlaub"],["travel","Reise"],["hotel","Hotel"],["map","Karte"],["country","Land"],
["culture","Kultur"],["history","Geschichte"],["future","Zukunft"],["past","Vergangenheit"],["present","Gegenwart"],
["weather","Wetter"],["wind","Wind"],["storm","Sturm"],["cloud","Wolke"],["sky","Himmel"],
["earth","Erde"],["fire","Feuer"],["air","Luft"],["energy","Energie"],["power","Kraft"],
["health","Gesundheit"],["sport","Sport"],["training","Training"],["running","Laufen"],["walking","Gehen"],
["swimming","Schwimmen"],["cycling","Radfahren"],["fitness","Fitness"],["strength","Stärke"],["rest","Ruhe"]
],

russisch: [
["яблоко","Apfel"],["дом","Haus"],["собака","Hund"],["кот","Katze"],["вода","Wasser"],
["книга","Buch"],["школа","Schule"],["машина","Auto"],["дерево","Baum"],["хлеб","Brot"],
["молоко","Milch"],["солнце","Sonne"],["луна","Mond"],["звезда","Stern"],["город","Stadt"],
["улица","Straße"],["телефон","Telefon"],["компьютер","Computer"],["стул","Stuhl"],["стол","Tisch"],
["окно","Fenster"],["дверь","Tür"],["цветок","Blume"],["сад","Garten"],["друг","Freund"],
["семья","Familie"],["любовь","Liebe"],["работа","Arbeit"],["деньги","Geld"],["время","Zeit"],
["день","Tag"],["ночь","Nacht"],["еда","Essen"],["напиток","Getränk"],["животное","Tier"],
["птица","Vogel"],["рыба","Fisch"],["гора","Berg"],["река","Fluss"],["море","Meer"],
["дождь","Regen"],["снег","Schnee"],["холод","Kälte"],["жара","Hitze"],["счастье","Glück"],
["грусть","Trauer"],["большой","Groß"],["маленький","Klein"],["быстрый","Schnell"],["медленный","Langsam"],
["свет","Licht"],["темнота","Dunkelheit"],["утро","Morgen"],["вечер","Abend"],["завтрак","Frühstück"],
["обед","Mittagessen"],["ужин","Abendessen"],["сыр","Käse"],["яйцо","Ei"],["мясо","Fleisch"],
["кофе","Kaffee"],["чай","Tee"],["сахар","Zucker"],["соль","Salz"],["перец","Pfeffer"],
["нож","Messer"],["вилка","Gabel"],["ложка","Löffel"],["тарелка","Teller"],["чашка","Tasse"],
["стакан","Glas"],["сумка","Tasche"],["рубашка","Hemd"],["штаны","Hose"],["обувь","Schuh"],
["куртка","Jacke"],["шапка","Hut"],["часы","Uhr"],["кольцо","Ring"],["кровать","Bett"],
["подушка","Kissen"],["одеяло","Decke"],["ванная","Badezimmer"],["кухня","Küche"],["пол","Boden"],
["стена","Wand"],["крыша","Dach"],["ключ","Schlüssel"],["замок","Schloss"],["автобус","Bus"],
["поезд","Zug"],["самолет","Flugzeug"],["билет","Ticket"],["станция","Bahnhof"],["аэропорт","Flughafen"],
["врач","Arzt"],["медсестра","Krankenschwester"],["больница","Krankenhaus"],["лекарство","Medizin"],["боль","Schmerz"],
["учитель","Lehrer"],["ученик","Schüler"],["урок","Unterricht"],["домашнее задание","Hausaufgabe"],["экзамен","Prüfung"],
["игра","Spiel"],["мяч","Ball"],["команда","Team"],["игрок","Spieler"],["гол","Tor"],
["музыка","Musik"],["песня","Lied"],["фильм","Film"],["картина","Bild"],["камера","Kamera"],
["новости","Nachrichten"],["газета","Zeitung"],["радио","Radio"],["телевидение","Fernsehen"],["интернет","Internet"],
["сайт","Webseite"],["пароль","Passwort"],["имя пользователя","Benutzername"],["кнопка","Knopf"],["экран","Bildschirm"],
["мышь","Maus"],["клавиатура","Tastatur"],["файл","Datei"],["папка","Ordner"],["загрузка","Download"],
["сообщение","Nachricht"],["чат","Chat"],["звонок","Anruf"],["голос","Stimme"],["язык","Sprache"],
["слово","Wort"],["предложение","Satz"],["вопрос","Frage"],["ответ","Antwort"],["идея","Idee"],
["план","Plan"],["проблема","Problem"],["решение","Lösung"],["работа","Job"],["офис","Büro"],
["встреча","Treffen"],["проект","Projekt"],["цель","Ziel"],["отпуск","Urlaub"],["путешествие","Reise"],
["отель","Hotel"],["карта","Karte"],["страна","Land"],["культура","Kultur"],["история","Geschichte"],
["будущее","Zukunft"],["прошлое","Vergangenheit"],["настоящее","Gegenwart"],["погода","Wetter"],["ветер","Wind"],
["буря","Sturm"],["облако","Wolke"],["небо","Himmel"],["земля","Erde"],["огонь","Feuer"],
["воздух","Luft"],["энергия","Energie"],["сила","Kraft"],["здоровье","Gesundheit"],["спорт","Sport"]
],

kurdisch: [
["sêv","Apfel"],["mal","Haus"],["kûçik","Hund"],["pisîk","Katze"],["av","Wasser"],
["pirtûk","Buch"],["dibistan","Schule"],["erebê","Auto"],["dar","Baum"],["nan","Brot"],
["şîr","Milch"],["roj","Sonne"],["heyv","Mond"],["stêr","Stern"],["bajar","Stadt"],
["kolan","Straße"],["telefon","Telefon"],["kompîter","Computer"],["kursî","Stuhl"],["masa","Tisch"],
["pace","Fenster"],["derî","Tür"],["gul","Blume"],["baxçe","Garten"],["heval","Freund"],
["malbat","Familie"],["evîn","Liebe"],["kar","Arbeit"],["dirav","Geld"],["dem","Zeit"],
["rojek","Tag"],["şev","Nacht"],["xwarin","Essen"],["vexwarin","Getränk"],["ajî","Tier"],
["bavik","Vogel"],["masî","Fisch"],["çiya","Berg"],["çem","Fluss"],["daryayê","Meer"],
["baran","Regen"],["berf","Schnee"],["sar","Kalt"],["germ","Heiß"],["şadî","Glücklich"],
["xem","Traurig"],["mezin","Groß"],["piçûk","Klein"],["zû","Schnell"],["hêdî","Langsam"],
["ronahî","Licht"],["tarî","Dunkel"],["sibeh","Morgen"],["êvar","Abend"],["taştê","Frühstück"],
["nîvro","Mittagessen"],["şîv","Abendessen"],["penîr","Käse"],["hêk","Ei"],["goşt","Fleisch"],
["qehwe","Kaffee"],["çay","Tee"],["şekir","Zucker"],["xwê","Salz"],["biber","Pfeffer"],
["kêr","Messer"],["çengal","Gabel"],["qeşoq","Löffel"],["tabax","Teller"],["fincan","Tasse"],
["qas","Glas"],["çente","Tasche"],["kiras","Hemd"],["şal","Hose"],["pêlav","Schuh"],
["kurt","Jacke"],["kef","Hut"],["saet","Uhr"],["angûst","Ring"],["nivîn","Bett"],
["balîf","Kissen"],["betanî","Decke"],["hammam","Badezimmer"],["metbex","Küche"],["erd","Boden"],
["dîwar","Wand"],["ban","Dach"],["kilît","Schlüssel"],["qefl","Schloss"],["otobûs","Bus"],
["trên","Zug"],["firok","Flugzeug"],["bilet","Ticket"],["stasyon","Bahnhof"],["balafirgeh","Flughafen"],
["bijîşk","Arzt"],["hemşîre","Krankenschwester"],["nexweşxane","Krankenhaus"],["derman","Medizin"],["êş","Schmerz"],
["mamoste","Lehrer"],["xwendekar","Schüler"],["ders","Unterricht"],["karê malê","Hausaufgabe"],["îmtîhan","Prüfung"],
["lîstik","Spiel"],["top","Ball"],["tîm","Team"],["lîstikvan","Spieler"],["gol","Tor"],
["muzîk","Musik"],["stran","Lied"],["fîlm","Film"],["wêne","Bild"],["kamera","Kamera"],
["nûçe","Nachrichten"],["rojname","Zeitung"],["radyo","Radio"],["televîzyon","Fernsehen"],["înternet","Internet"],
["malpera web","Webseite"],["şîfre","Passwort"],["navê bikarhêner","Benutzername"],["dugme","Knopf"],["ekran","Bildschirm"],
["mişk","Maus"],["klavye","Tastatur"],["pel","Datei"],["peldank","Ordner"],["daxistin","Download"],
["peyv","Nachricht"],["çet","Chat"],["bang","Anruf"],["deng","Stimme"],["ziman","Sprache"],
["gotin","Wort"],["hevok","Satz"],["pirs","Frage"],["bersiv","Antwort"],["fikir","Idee"],
["plan","Plan"],["pirsgirêk","Problem"],["çareserî","Lösung"],["ofîs","Büro"],["hevdîtin","Treffen"],
["proje","Projekt"],["armanc","Ziel"],["betlanê","Urlaub"],["sewahat","Reise"],["otel","Hotel"],
["xerîte","Karte"],["welat","Land"],["çand","Kultur"],["dîrok","Geschichte"],["pêşeroj","Zukunft"],
["borî","Vergangenheit"],["niha","Gegenwart"],["hewa","Wetter"],["bay","Wind"],["tûfan","Sturm"],
["ewr","Wolke"],["ezman","Himmel"],["erd","Erde"],["agir","Feuer"],["hewa","Luft"],
["enerjî","Energie"],["hêz","Kraft"],["tenduristî","Gesundheit"],["spor","Sport"]
]

};

